# Generated by Django 4.1.3 on 2022-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramgraph',
            fields=[
                ('nomgraph', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('param1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paramgraph',
            },
        ),
    ]
