# Generated by Django 4.1.3 on 2022-12-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_paramgraph_id_paramgraph_auto_increment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paramgraph',
        ),
    ]
