# Generated by Django 4.1.3 on 2022-11-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factures',
            fields=[
                ('nofacture', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('datefacturation', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'factures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('codeproduit', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'produits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('nofacture', models.OneToOneField(db_column='nofacture', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.factures')),
                ('qte', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contenir',
                'managed': False,
            },
        ),
    ]
