# Generated by Django 4.1.3 on 2022-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_paramgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramgraph',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paramgraph',
            name='nomgraph',
            field=models.CharField(max_length=50),
        ),
    ]
