# Generated by Django 4.1.3 on 2022-12-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_paramgraph_id_alter_paramgraph_nomgraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramgraph',
            name='id',
        ),
        migrations.AddField(
            model_name='paramgraph',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
