# Generated by Django 4.1.3 on 2022-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_paramgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramgraph',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('nomgraph', models.CharField(max_length=50)),
                ('param1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paramgraph',
            },
        ),
    ]
