# Generated by Django 4.1.3 on 2022-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_paramgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramgraph',
            name='param2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
